import typing
from dataclasses import dataclass

text = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus mattis lacinia. Etiam lectus erat, convallis id porta vel, accumsan eleifend mi. Proin nec eros cursus justo molestie dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ut purus massa. Maecenas vehicula commodo elit, a vestibulum purus dapibus auctor. Quisque condimentum in neque at dictum. Cras imperdiet metus quam, nec venenatis tellus finibus vitae. Fusce at sem hendrerit, tristique lorem non, efficitur velit. Integer euismod tellus nisl, et ultricies justo varius dapibus. Pellentesque cursus felis a nibh rutrum accumsan. Donec tempor sed risus non pellentesque.

Duis leo ante, ullamcorper nec tellus sit amet, eleifend volutpat velit. Phasellus euismod dui sed quam varius, sed convallis augue luctus. Cras in scelerisque purus, eu porta est. Integer quis placerat felis. Donec quis diam nisl. Ut rutrum pharetra lacinia. Etiam quis sapien quis purus pulvinar auctor eu nec libero. Morbi eleifend non orci at mollis. Sed mollis eros in mollis euismod. Morbi risus neque, ultrices et leo sit amet, aliquet congue massa. Maecenas convallis ipsum eget nisi vehicula iaculis. Sed lorem lectus, tincidunt quis posuere sed, placerat eget turpis. Vestibulum semper felis non mauris congue porttitor. Donec quis efficitur metus.

Morbi iaculis vehicula maximus. Integer laoreet, arcu aliquet aliquam bibendum, est ipsum mollis sem, non condimentum magna lorem non ex. Vestibulum convallis mattis nisi. Ut vel sem neque. Etiam convallis arcu at nunc luctus, facilisis ultrices odio mollis. Maecenas nec hendrerit risus. Pellentesque imperdiet velit ante, in placerat ante placerat sed. Nullam tristique quis ex et imperdiet. Aenean vel felis at erat euismod accumsan eget eget sapien. Sed condimentum purus lorem, eu pharetra nibh tempus at. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam vitae tortor vel neque dapibus pretium. Ut molestie, ligula non porttitor laoreet, eros urna pretium purus, sed porta ex tellus fringilla ante. Vivamus vehicula porttitor dui. Etiam sit amet vestibulum eros, vitae pellentesque eros. Sed eu enim est.

Suspendisse viverra dapibus ex, vel rhoncus dui pulvinar sed. Morbi quis orci leo. Vestibulum nec arcu lorem. Sed pulvinar metus sed efficitur faucibus. Nullam commodo sollicitudin orci venenatis ultricies. Suspendisse tristique consectetur auctor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nec vehicula sapien. Praesent consequat lectus id ex malesuada molestie. Maecenas tortor metus, gravida a ullamcorper vel, tempor sed diam.

Donec vitae bibendum enim. Donec at ex id ligula venenatis dictum. Sed venenatis arcu non lorem consectetur, in pulvinar justo ornare. Nullam faucibus sapien vel sem aliquet, ut euismod risus convallis. Pellentesque euismod leo vitae eros ornare, in suscipit felis ultrices. Nullam turpis nunc, efficitur varius eleifend sed, vehicula id magna. Etiam euismod purus id facilisis iaculis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eget malesuada sem. Cras molestie vestibulum ante, a lobortis odio maximus sit amet. Nunc volutpat vehicula ante, porttitor interdum purus ultrices eget. Quisque ipsum enim, pretium sit amet condimentum id, mollis at risus. Maecenas odio turpis, varius ut mollis vitae, finibus a sem. Integer vel purus interdum, gravida metus gravida, faucibus dui.

Vestibulum sit amet facilisis ipsum. Maecenas luctus dictum urna sit amet porta. Fusce et euismod elit. Proin ut diam eget nibh lacinia cursus id vitae justo. Morbi convallis libero vel sollicitudin pellentesque. Proin volutpat sapien ex, sit amet volutpat arcu bibendum porta. Sed eget rutrum dui. Quisque blandit suscipit accumsan. Sed condimentum, tellus vitae tristique dictum, odio diam ullamcorper mauris, nec placerat augue leo non augue. Donec tortor leo, aliquam sit amet purus a, venenatis pharetra tortor. Suspendisse aliquam aliquam rutrum. Integer consequat augue enim, ut scelerisque risus posuere eget. Aenean accumsan libero a nisl dapibus dictum. Morbi justo neque, aliquam tincidunt nisl eu, ullamcorper tempus tellus.

Ut vestibulum aliquet mauris, vitae venenatis mi consequat sed. Ut congue tempus bibendum. Aliquam rhoncus turpis a ex venenatis, id cursus ante efficitur. Curabitur venenatis fringilla maximus. Etiam sed faucibus orci. Nam auctor, orci porttitor dapibus consequat, dui velit vehicula magna, ac aliquet dolor leo id nunc. Donec laoreet mi mi, ut ornare tellus commodo tempor. Vivamus quis eros vitae tellus condimentum placerat. Vivamus eu augue at felis vehicula consequat eget quis nulla. Morbi posuere urna non elit aliquam, ac bibendum justo luctus.

Donec enim quam, finibus nec rutrum eu, pulvinar non dolor. Donec vitae consectetur odio, non viverra massa. Phasellus pellentesque leo vel justo auctor, non consectetur tortor aliquam. Etiam id enim ac odio pretium fringilla. Sed volutpat enim eget libero luctus, sed posuere neque viverra. Vivamus ligula quam, condimentum a feugiat in, rutrum vitae nulla. Ut faucibus dolor a ex rutrum dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc urna felis, consequat id nibh non, accumsan suscipit nisi. Nunc mattis iaculis diam. Duis commodo consectetur eleifend. In rutrum blandit maximus. Sed vel nunc lacus. Ut aliquam convallis tellus, iaculis convallis neque convallis vitae.

Vestibulum suscipit maximus enim, non tincidunt lectus aliquet nec. Vivamus ut accumsan lacus. Fusce id leo in nibh gravida ornare. Mauris rhoncus porta lacus, vel facilisis dui. Etiam ullamcorper lorem tellus, ut ultrices tortor blandit ut. Proin mauris justo, semper eu convallis sit amet, egestas ut ipsum. Cras et eleifend neque, a eleifend est. Sed mattis nibh non dapibus congue. Phasellus vulputate viverra sodales. Aenean nec mi lacus. Pellentesque scelerisque bibendum aliquet. Duis ut nisl a dui congue aliquam.

Suspendisse potenti. Aliquam eget imperdiet dolor, quis vestibulum dui. Sed pharetra nulla nec dui suscipit pharetra. Nulla facilisi. Fusce est sem, sollicitudin sed dictum in, lacinia eu tellus. Nunc quis enim sit amet eros aliquam aliquet faucibus ut ex. Vestibulum euismod facilisis risus a varius. Cras imperdiet vel nisi a pulvinar. Vivamus neque quam, faucibus vel ultricies non, dignissim sit amet lorem. Pellentesque quis condimentum quam, at gravida massa. Nullam sollicitudin non ligula sodales vehicula. Proin congue elit quis dolor faucibus, eget commodo arcu ullamcorper.

Vestibulum gravida aliquam purus ac rhoncus. Integer non mauris non ante convallis ornare. Quisque at felis ultrices arcu viverra laoreet. Proin in lacinia odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean eget nibh urna. Duis nec odio vulputate, pharetra dui eget, ultrices ante. Maecenas maximus interdum lacinia. Nunc fringilla aliquam leo vitae gravida. Curabitur semper dolor vitae finibus rhoncus.

Vestibulum rhoncus sapien eu interdum lobortis. Ut ut dapibus nunc. Curabitur varius, magna in posuere pretium, neque ex tincidunt mauris, vitae commodo eros dui sit amet magna. Phasellus vestibulum quam ut lorem vehicula sollicitudin. Fusce malesuada urna eget nibh feugiat commodo vitae vel risus. Vivamus efficitur semper urna at rutrum. Praesent vel semper risus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In hac habitasse platea dictumst. Aliquam ultricies justo risus, sed scelerisque massa mollis nec. Cras eu pulvinar lectus. Aliquam erat volutpat. In bibendum sem a nibh ullamcorper, vel volutpat est ornare. Donec id dignissim ex. Suspendisse dictum nisl quis convallis euismod.

Quisque tincidunt vulputate risus sed lobortis. Fusce et risus libero. Nullam scelerisque porta sem et feugiat. Vestibulum vulputate augue at dolor rhoncus, non venenatis purus mollis. Aenean vitae aliquet arcu, a semper purus. Fusce quam diam, venenatis eu metus bibendum, dignissim cursus ex. In dictum risus et odio facilisis scelerisque. Cras at blandit libero.

Nam vitae tortor ipsum. Praesent volutpat tempus velit, eu pretium diam lobortis nec. Nullam faucibus condimentum tristique. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tempus, libero quis accumsan porta, nunc purus auctor nunc, a convallis ante mauris sed nibh. Sed tincidunt volutpat felis, nec fringilla ex tempus vel. Phasellus tempus odio velit, sit amet blandit lorem rutrum vitae. Maecenas venenatis sagittis magna nec sagittis. Integer gravida, lorem at dignissim feugiat, ante ante rutrum risus, vitae efficitur nisi metus et justo. Aenean tempor malesuada euismod. Cras vulputate eros semper, semper velit ut, elementum nunc.

Quisque a elit sed justo blandit vehicula et sed metus. Duis sit amet risus metus. Aenean commodo lacus vel arcu consequat semper. Phasellus lorem nibh, venenatis et hendrerit mollis, fermentum vel leo. Praesent pellentesque ornare porta. Aliquam ornare molestie mauris, sed ullamcorper mi rhoncus eu. Nullam suscipit lobortis justo ac sodales. Quisque semper, turpis quis laoreet commodo, magna sapien placerat urna, non sagittis ex quam non tellus. Fusce laoreet turpis velit, ac consequat dolor molestie non. Sed est est, elementum nec lorem vel, mollis pretium ipsum. Fusce ut venenatis risus, vel cursus orci.

Duis quam magna, finibus non mi eu, maximus porta est. Aenean sit amet nisl scelerisque, sodales mauris eget, finibus enim. Quisque vitae erat purus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec molestie neque sit amet mi aliquam commodo. Praesent blandit ut nisi in consequat. Duis euismod, lacus in maximus auctor, nunc urna pretium nisl, ut placerat lectus ex nec lacus. Curabitur pharetra nunc lorem. Donec lacus augue, blandit et gravida at, vehicula ut ex. In ac neque tincidunt, pretium ex non, ornare diam.

Cras eget sagittis metus. Curabitur aliquam nisi a ligula aliquam lobortis. Sed vitae eleifend erat. Curabitur ut elit porta, consequat purus eget, maximus quam. Donec purus felis, placerat nec rutrum ut, finibus vitae risus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eleifend dictum felis nec auctor. Morbi porttitor orci id dictum mollis. Nullam rhoncus sit amet ligula nec tincidunt. Maecenas sit amet dolor nec risus mollis commodo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vel elit luctus, rutrum diam id, pretium felis. Nunc vel leo dui. Duis sed ex nec enim volutpat ultricies.

Vestibulum hendrerit arcu urna, et maximus nibh semper et. Donec convallis tempus turpis ut congue. Proin eu enim dui. Nulla facilisi. Quisque commodo urna vitae urna scelerisque vestibulum. In id justo ex. Quisque ac arcu in neque bibendum sollicitudin vel eu ante. Integer nec blandit mauris. Cras non elit tortor.

Cras consequat, augue a suscipit sagittis, ex purus pulvinar turpis, vel dapibus mi erat eget neque. Maecenas id facilisis neque. Maecenas lorem nunc, vehicula ac malesuada vel, viverra sit amet metus. Donec in magna pretium, dapibus orci pretium, blandit nisi. Donec sed lacus eget sem bibendum molestie. Nulla vel odio sed nunc dignissim posuere. Curabitur pharetra et augue nec pulvinar. Sed in dapibus ligula. Phasellus est dui, mollis vitae consequat eget, tempor non leo. Nulla odio arcu, dapibus nec elit nec, ultricies egestas odio. Proin mollis felis a lorem tristique tristique. Integer et molestie mauris. Pellentesque eget tortor blandit, pharetra neque vel, sollicitudin nisl.

Integer posuere urna eu felis fringilla malesuada. Nam maximus consequat arcu, eget sagittis metus dapibus sed. Fusce consectetur eget nisi a laoreet. Vestibulum et mauris facilisis, rhoncus libero nec, pretium urna. Maecenas condimentum sit amet tellus id vulputate. Nunc malesuada rutrum erat at convallis. Curabitur vitae laoreet orci, vitae eleifend orci. Pellentesque sagittis nibh ut libero luctus, non imperdiet lectus rutrum. Phasellus eu arcu sed diam porta vestibulum a et dolor.

Curabitur molestie felis leo, id interdum ipsum feugiat in. Vivamus non nibh ut dui ornare feugiat. Etiam a tortor nunc. Etiam commodo blandit leo, eget pretium dolor fermentum non. Proin tempus blandit urna. Etiam euismod elit neque, eget mattis purus viverra sed. Maecenas quis pellentesque lacus. Aenean tempor vel enim at dapibus. Donec et ante non dui porttitor finibus eu ornare nibh. In quis ante congue, condimentum elit vitae, bibendum quam. Donec pharetra elementum tortor nec aliquet.

Vestibulum vitae congue libero. Donec vitae ligula eu arcu malesuada ultricies a eget dui. Sed vitae mauris venenatis, euismod nisl a, eleifend nisl. Sed sapien elit, blandit quis volutpat eget, viverra iaculis leo. Duis sodales nisl nec nulla condimentum, nec dignissim elit blandit. Nulla et convallis quam. Sed molestie, ligula id sollicitudin iaculis, metus tortor malesuada tortor, eu gravida dui mi non libero. Ut id nunc sollicitudin, commodo est in, malesuada lacus. Nullam vestibulum turpis lectus, ac venenatis orci suscipit ac. Quisque ante urna, auctor ultrices consectetur eu, tempus sit amet neque. Phasellus in ultrices nisl, eu posuere tortor.

Quisque laoreet mauris molestie felis fringilla, et finibus lorem rutrum. Aliquam mattis urna metus, id gravida massa ullamcorper vitae. Cras placerat efficitur sodales. Donec erat libero, placerat nec erat mollis, molestie venenatis lectus. Proin sed convallis lectus, quis fringilla orci. Donec commodo dui quis sodales accumsan. Fusce convallis accumsan est id tincidunt. In vestibulum augue quis odio vulputate, vitae imperdiet elit mollis. Morbi pulvinar justo a mollis eleifend. Sed posuere dolor eu urna tristique dignissim. Pellentesque imperdiet eget lectus varius luctus.

In lacus velit, iaculis gravida condimentum ut, vulputate volutpat massa. Cras non pulvinar turpis, at semper enim. Donec iaculis lobortis porta. Duis rhoncus sit amet metus at ullamcorper. Etiam in urna odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc facilisis, ex a vestibulum viverra, arcu diam ullamcorper massa, id aliquam ipsum velit sed turpis.

Sed aliquet, risus vel dictum congue, ligula eros consectetur metus, ut consequat tellus nibh a nunc. Etiam gravida gravida nibh, a lobortis ipsum ornare sed. Sed sed ex volutpat, posuere mi ac, euismod ex. Donec sed dapibus nulla, nec imperdiet arcu. Proin consectetur vitae velit vitae auctor. Donec bibendum ex at mattis dictum. Nam egestas quam ut aliquet maximus. Sed eget nibh luctus, egestas metus sed, interdum lorem. Nunc in mi lacus. Pellentesque vitae rhoncus enim, eget congue odio. Integer et magna dapibus, tristique nulla in, dictum magna. Ut nec justo eu diam venenatis dapibus nec id eros. Suspendisse maximus libero sit amet lacus venenatis, vitae fringilla nibh ullamcorper. Aliquam erat volutpat. Ut porttitor nulla tortor, sed tempus magna tempus ac.

Nulla tincidunt semper risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque suscipit lacinia enim, eu molestie risus. Ut in rhoncus dui. Sed hendrerit, purus quis interdum dictum, lorem nisi dapibus turpis, sed hendrerit libero ligula a risus. Sed suscipit erat non laoreet ullamcorper. Ut auctor pulvinar justo, non mollis elit suscipit nec. Maecenas placerat dapibus arcu eget elementum.

In eget nibh scelerisque, suscipit elit nec, sollicitudin leo. Fusce posuere elementum nisi ac vulputate. Donec laoreet rhoncus scelerisque. Sed eu libero maximus, hendrerit sem laoreet, ultrices lorem. Donec interdum viverra massa. Phasellus molestie volutpat tempus. Aenean blandit condimentum enim. Cras non magna ut nisl ullamcorper facilisis at a ipsum. Aliquam et nulla non dui interdum commodo at eget urna.

Quisque egestas diam a neque mollis porta. Ut in magna in augue vestibulum commodo. Integer at arcu lacus. Donec rutrum, ante placerat fringilla vulputate, sapien odio feugiat turpis, ac viverra lectus justo a dolor. Donec eu leo nibh. Etiam condimentum sodales orci, at tristique ex tempor eu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed condimentum justo sit amet diam finibus, id dignissim ligula tempor. Praesent sed sapien vitae felis malesuada imperdiet. Nulla vitae leo nunc. Aliquam viverra diam neque, at luctus sem pulvinar sodales.

Praesent a nunc urna. In pharetra eros libero, in rutrum quam tempus quis. Ut nisl lacus, eleifend nec nibh vel, interdum fringilla dolor. Aliquam placerat mi sollicitudin ullamcorper laoreet. Phasellus dapibus quam eget viverra feugiat. Aliquam ut scelerisque sapien, et cursus est. Nunc luctus augue eu enim iaculis, vel consectetur sem lacinia. Nullam vehicula massa a luctus aliquet. Nunc massa lorem, mollis vitae fringilla a, malesuada vel metus. Morbi nunc sapien, mollis eget scelerisque sit amet, luctus ut augue. Pellentesque quis tortor sed leo consectetur auctor. Fusce pellentesque lorem at tincidunt euismod. Nullam lobortis tincidunt sodales. Suspendisse ut nunc aliquam, sagittis sapien at, facilisis enim.

Morbi a posuere lorem. Suspendisse in tempor nibh, ac venenatis ipsum. Vestibulum efficitur erat arcu, id condimentum ipsum dignissim ac. Sed ac mauris sollicitudin turpis semper consequat quis vitae mauris. Quisque nec elementum nisi. Integer luctus urna iaculis imperdiet ultricies. Quisque tempor risus in tortor elementum auctor. Nulla ullamcorper quis ipsum a semper. Aliquam ut viverra est. Ut ut nisl vehicula, aliquet sem ac, mattis nisi.

Nullam mollis, sem ut sollicitudin pellentesque, nibh risus luctus nisl, et pretium dui nisl eget nulla. Integer nec augue finibus, ultricies tortor a, pharetra purus. In bibendum turpis et dui ultricies, ac finibus mi elementum. Sed facilisis lorem vel metus lobortis, non pretium quam placerat. Vestibulum odio magna, accumsan et magna in, facilisis pulvinar nisi. Mauris vel tincidunt lorem. Proin at dolor sed justo volutpat malesuada sed sit amet urna. Donec non odio nec nibh bibendum consequat. Praesent rutrum urna ut accumsan sagittis. Donec laoreet tincidunt turpis ac condimentum. Aliquam convallis rhoncus massa, et rutrum dolor faucibus ac. Proin pharetra tempor orci. Aenean feugiat, ante quis feugiat pharetra, tortor risus ornare augue, quis posuere nulla tortor at augue. Etiam eu venenatis nulla. Nam a purus nec purus dapibus fermentum in non erat. Nulla auctor euismod enim at faucibus.

Vivamus finibus sem a tellus malesuada, eget varius nisl gravida. Curabitur turpis sapien, luctus id bibendum non, varius eget massa. Nam consequat in sem elementum lacinia. Cras euismod elit eget sapien rutrum, eu commodo est eleifend. Fusce tincidunt gravida ornare. Cras mattis nisi nec eros placerat, at maximus tellus tincidunt. Sed quis consequat quam, eget malesuada nibh. Nunc non sem eu massa aliquam mollis in in ex. Aenean sit amet egestas orci, ac blandit enim.

In quis sapien sed lectus rutrum hendrerit. Fusce vitae faucibus lorem, vel ullamcorper eros. Quisque vel ultrices enim. Vestibulum efficitur eleifend turpis sed maximus. Nulla metus nulla, molestie eu ornare id, pretium in nulla. Aenean non accumsan ex. Vestibulum luctus sem libero, eget dapibus sapien ullamcorper in. Nunc eleifend urna at ante elementum, vitae interdum eros suscipit. In eros eros, porta hendrerit interdum vitae, mattis viverra lacus. Sed non nisi vel eros accumsan porttitor eu varius diam. Pellentesque ut facilisis nibh. Suspendisse eget lorem ac lectus viverra porta eu at velit.

Nulla facilisi. Sed ut dui risus. Sed et ligula nulla. Etiam a turpis ac libero aliquet molestie sit amet at mauris. In vitae iaculis erat, id luctus nisi. Quisque sed efficitur nibh, et posuere arcu. Donec maximus varius elit, non varius leo egestas non. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque ante felis, posuere eget venenatis et, sagittis ac est. Vestibulum odio arcu, auctor ac mauris vitae, dignissim hendrerit turpis. Ut sit amet ligula ut sem tristique tincidunt eu eget mi. Aliquam erat volutpat. Vivamus porttitor dui ut felis efficitur, nec laoreet dui ultrices.

Aenean mollis nisl purus, quis pulvinar lorem ultrices lacinia. Morbi pretium purus vel venenatis sodales. Proin fermentum massa eget nibh interdum vulputate. Nullam at lacus suscipit, semper velit a, tincidunt velit. Quisque gravida leo eu posuere malesuada. Phasellus convallis odio at eros ullamcorper eleifend. Vivamus at finibus tortor. Mauris laoreet erat mauris. Nulla facilisi. Vivamus egestas molestie justo, non ornare augue consequat ac. In congue a ipsum sit amet cursus. Aenean pretium tortor eu enim porta consequat. Pellentesque interdum ultrices ante. Suspendisse nec erat sapien. Integer quis imperdiet nisi. Sed vitae ullamcorper risus.

Donec accumsan leo sit amet quam congue, quis fermentum augue faucibus. Curabitur luctus elit non dolor mollis hendrerit sit amet nec lorem. Praesent porta ligula erat, at facilisis lectus pellentesque vel. Nunc ac rutrum purus, eget maximus ligula. Nullam elit elit, eleifend nec justo vitae, luctus porttitor lectus. Vivamus suscipit nisi sed leo rhoncus cursus. Sed at condimentum sapien, vitae facilisis dolor. Quisque sollicitudin lacus et mi fringilla, non pharetra arcu interdum. Integer consectetur semper urna ut feugiat. Integer tristique congue orci nec egestas. Praesent volutpat iaculis libero vitae euismod. Sed at metus a libero luctus mattis at fringilla leo.

Maecenas suscipit, est sit amet consequat semper, odio turpis placerat massa, eget placerat ligula nunc ut lacus. Phasellus sodales tempor tellus sit amet volutpat. Proin quis faucibus arcu. Cras pulvinar, dui in luctus rhoncus, felis nisl pretium velit, vel imperdiet est sem et nibh. Aenean eu massa euismod, blandit ante nec, accumsan augue. Nunc aliquam tincidunt vehicula. Quisque bibendum pretium sodales. Nunc nec odio sit amet ligula maximus hendrerit. Maecenas ut arcu cursus, porttitor est quis, placerat felis. Vivamus auctor vestibulum bibendum. Praesent vel ex lacus. In in mi massa. Aenean eget cursus elit, quis dictum felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc semper et ante et placerat. Praesent eu ex ut quam cursus varius.

Vestibulum non pulvinar lacus. Suspendisse maximus volutpat tincidunt. In volutpat diam sagittis, ultricies sapien ut, vehicula mi. Cras maximus vitae dolor a tempor. Nulla commodo tellus a diam cursus, sed venenatis enim faucibus. Duis vitae lectus non odio luctus cursus vitae vitae elit. Donec rhoncus pretium justo, et feugiat metus sollicitudin at. In ac lacus et est ultricies rhoncus et sit amet augue. Nulla sollicitudin, libero eu scelerisque rutrum, massa velit placerat nulla, non auctor dolor lacus a tellus.

Sed pellentesque arcu et nunc volutpat, pharetra consectetur justo ornare. Fusce ultrices nisl quis nulla iaculis, quis tempus est malesuada. In ut nisl eu neque lacinia vestibulum. Donec sit amet aliquam magna. Nunc quis fringilla eros, et auctor ante. Nam arcu felis, lacinia eget accumsan eget, porttitor quis tellus. Nunc venenatis enim vitae eros condimentum eleifend.

Cras vel aliquet ligula, non placerat est. Donec non auctor lorem, sit amet pulvinar magna. Vestibulum id enim dui. Nullam dui arcu, ullamcorper sit amet augue sed, pharetra malesuada urna. Aenean et quam nec enim dapibus venenatis. Pellentesque sit amet ultrices purus. Nulla tempus faucibus ipsum a ullamcorper. Nulla sit amet diam orci. Vestibulum ac arcu odio. Quisque id pharetra purus. Sed odio ex, ullamcorper euismod tempor lacinia, luctus eu eros. Nulla a tortor at nulla luctus malesuada non eu magna.

Morbi sed lectus eleifend, consequat sem et, rhoncus mi. Proin sit amet orci et nunc condimentum pretium vitae a tortor. Nunc at ligula ultricies, euismod turpis non, feugiat lorem. Integer semper placerat felis eget luctus. Sed quis faucibus dolor. Phasellus porta at velit nec tristique. Morbi ornare diam quam, quis fermentum sapien luctus eget. Nullam suscipit a leo a viverra. Aenean ullamcorper efficitur est. Vestibulum accumsan ullamcorper porttitor. Mauris vehicula purus id risus mollis, vel sollicitudin orci dapibus.

In hac habitasse platea dictumst. Integer eu odio a arcu tincidunt consectetur. In cursus sapien non ex rutrum, nec pharetra tellus mollis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis purus sit amet ligula lobortis scelerisque non id erat. Nullam a consectetur lorem. Fusce semper augue massa, eu interdum libero ornare pharetra. Nulla facilisi. Aliquam egestas ipsum dapibus, consequat mi sit amet, sodales orci.

Donec nec enim quis nunc venenatis pulvinar sit amet a quam. Aenean nec nunc varius, ultrices ante sed, euismod ipsum. Fusce tincidunt est vel leo tincidunt viverra. Nunc elementum, ex id sagittis convallis, leo augue facilisis justo, at aliquet ipsum dui sed orci. Morbi sagittis massa purus, in egestas erat aliquet nec. Maecenas convallis nunc felis, cursus rhoncus erat porttitor ut. Nam aliquet consequat lorem, sed condimentum tortor lobortis non.

Pellentesque hendrerit justo vel nibh iaculis, vitae interdum eros auctor. Donec et magna at nisl dapibus tristique et vitae neque. Donec faucibus scelerisque urna nec rutrum. Aliquam vehicula ut lacus non tempor. Fusce volutpat ultricies porta. Donec efficitur hendrerit tellus. Suspendisse congue sapien ac arcu rutrum tincidunt. Quisque molestie, dolor eu posuere ornare, libero ante interdum mi, nec aliquet mi justo sollicitudin mauris. Quisque fringilla ut dolor sit amet placerat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Proin congue convallis justo, sit amet dapibus ex gravida tincidunt. Etiam leo enim, faucibus eget tincidunt sed, blandit vel eros. Donec in dui elit. Nulla et fermentum diam. Etiam vehicula lorem et quam pharetra lobortis. Donec in mauris euismod, elementum purus at, malesuada eros. Duis nec nisl nec elit feugiat consectetur in eget ligula. Etiam tortor mauris, vehicula id erat ac, tincidunt suscipit lacus. Cras pharetra ante non dui dictum, a luctus lorem consequat. Etiam luctus risus ut malesuada accumsan. Aliquam ut magna in mi tincidunt venenatis sit amet non mi. Vivamus sed libero ac ipsum efficitur tincidunt non eu nibh. Mauris lectus lectus, consequat vehicula hendrerit sed, cursus ut risus.

Vestibulum viverra massa erat, ac blandit ligula congue at. Nunc lectus erat, viverra at mi vel, tristique pharetra dui. Etiam sagittis sollicitudin ligula, a interdum sem iaculis et. Curabitur imperdiet at dui convallis convallis. Praesent ultricies vulputate felis vitae eleifend. Praesent urna risus, finibus id consectetur eu, pellentesque id velit. Cras accumsan posuere erat, non hendrerit lectus efficitur placerat. Sed vitae erat nunc. In in diam id turpis consectetur dictum sit amet non ligula. Donec vel lobortis massa. Fusce ac risus eget sapien posuere tristique vitae vitae est.

Nunc eu posuere est. Nulla placerat iaculis augue, et dapibus lorem mattis vel. Cras metus arcu, condimentum ut tincidunt in, tempus tempus libero. Praesent eu magna quis diam mattis porta sed eget metus. Ut nec augue nec neque viverra aliquam. Donec porta ante vitae ipsum pellentesque luctus. Vivamus vel commodo eros. Etiam ac lorem elit. Sed aliquet aliquam tempor. Phasellus in egestas ex, sit amet venenatis orci. Mauris quis metus urna. Nunc interdum mattis porttitor.

Praesent sed convallis mauris. Praesent sollicitudin metus enim, non volutpat sapien semper consectetur. Nam urna lectus, efficitur eget orci eu, iaculis fermentum tellus. Quisque ligula diam, efficitur eget consequat eget, pharetra vitae arcu. Phasellus aliquet ullamcorper bibendum. Maecenas ut eleifend erat. Vivamus quis mi ac nibh malesuada scelerisque eget non urna. Etiam non pretium orci. Sed consectetur et ante eu finibus. Mauris accumsan lacus ac augue eleifend dictum. Quisque semper elit at quam dictum pretium. Pellentesque quis risus tortor. Proin sodales turpis eget ex egestas pretium. Aliquam blandit malesuada dolor, quis facilisis quam lobortis malesuada. Nam tristique nunc et diam tincidunt varius.

Fusce in dolor at sapien hendrerit tempus in ac lorem. Etiam dui libero, pharetra non dignissim sed, venenatis nec purus. Curabitur placerat non ex at scelerisque. Pellentesque lacinia ullamcorper lacinia. Aenean tristique metus eget pharetra accumsan. Ut sollicitudin eros quis tristique aliquet. Quisque diam ante, dignissim volutpat risus a, sodales commodo nulla. Proin ac odio ut sem fermentum ultrices. Fusce finibus faucibus leo, eu porta mi fermentum vitae. Etiam laoreet augue sit amet nisi tincidunt, a consequat dui euismod.

Nullam non pulvinar libero. Nulla at dui eu orci tincidunt feugiat. Phasellus vulputate condimentum porta. Etiam faucibus metus et ipsum accumsan, ac bibendum metus eleifend. Aliquam tortor mauris, consequat vitae condimentum id, porttitor et dui. Morbi ac sapien tellus. Etiam diam ligula, tincidunt quis facilisis sit amet, ullamcorper in sapien. Sed efficitur massa sit amet metus congue laoreet. In nec tincidunt quam, eget viverra felis. Donec ornare, mi sed porttitor semper, leo nibh tincidunt felis, vel aliquet purus elit sed magna."""


@dataclass
class ReservWords():
    lorem: str = text
    ассаламалейкум: str = "ассаламалейкум дон"
    динах: tuple = ("иди нахуй", "динах", "иди нах", "идинах", "идиди", "нахуй иди", "пидорас")
